- include: update_apt_via_module.yml
- name: Enable apt to use a package repository via HTTPS
  when: ansible_os_family == 'Debian'
  become: yes
  become_user: root
  apt:
    pkg: "{{ item }}"
    state: latest
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
