- include: update.yml
- name: cargo -> install -> rust
  become: yes
  become_user: root
  command: command -v "cargo" >/dev/null 2>&1 || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
- name: cargo -> install -> packages
  become: yes
  become_user: root
  command: cargo install "{{ item }}"
  loop:
    # Drill is a HTTP load testing application written in Rust inspired by Ansible syntax 
    - drill
