- include: update.yml
- name: Elixir -> Add apt repository
  when: ansible_os_family == 'Debian'
  become: yes
  become_user: root
  apt:
    deb: https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
- include: update_apt_via_module.yml
- name: Elixir -> Install packages -> via apt
  when: ansible_os_family == 'Debian'
  become: yes
  become_user: root
  apt:
    pkg: "{{ item }}"
    state: latest
  loop:
    - esl-erlang
    - elixir
- name: Elixir -> Install packages -> via dnf
  when: ansible_os_family == 'RedHat'
  become: yes
  become_user: root
  dnf:
    pkg: "{{ item }}"
    state: latest
  loop:
    - esl-erlang
    - elixir
