- name: Update dnf via module -> latest
  when: ansible_os_family == 'RedHat'
  become: yes
  become_user: root
  dnf:
    name: '*'
    state: latest
    update_cache: yes
- name: Update dnf via module -> autoremove
  dnf:
    autoremove: yes
  