- name: Update apt via module
  when: ansible_os_family == 'Debian'
  become: yes
  become_user: root
  apt:
    update_cache: yes
    upgrade: full
    autoclean: yes
    autoremove: yes
    purge: yes
