- name: Update apt via command
  when: ansible_os_family == 'Debian'
  become: yes
  become_user: root
  command: "apt-get --quiet --yes {{ item }}"
  loop:
    - "update --fix-missing"
    - "upgrade --fix-broken --fix-missing"
    - "dist-upgrade --fix-broken --fix-missing"
    - "full-upgrade --fix-broken --fix-missing"
